Feature/cfg 20
DmitriyBrewer/CodersForceGame pull request #35
Opened 2024-06-11 15:16 UTC by Anastasiia171

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-06-12 11:44 UTC, fxmxa requested changes

2024-06-12 11:44 UTC, fxmxa commented on packages/client/src/feature/session/api/authApi.ts
> +    result.data = { message: 'OK' }
Отлично придумано

2024-06-12 11:44 UTC, fxmxa commented on packages/client/src/feature/session/login/hooks/useLogin.tsx
> +      const typedError = err as LoginApiError
тут тип ошибки  4хх , но она не попадет в catch. Если запрос возвращает код ошибки то это считается успешным запросом. Сюда попадет например ошибка сети. Надо добавить if (!response.ok) в customBaseQuery и там выбрасывать ошибку

2024-06-12 14:42 UTC, Anastasiia171 commented on packages/client/src/feature/session/login/hooks/useLogin.tsx
> +      const typedError = err as LoginApiError
добавила

2024-06-12 15:53 UTC, fxmxa commented on packages/client/src/feature/session/login/hooks/useLogin.tsx
> +      const typedError = err as LoginApiError
Так тоже не сработает это обычный объект возвращается и не считается ошибкой. Можно например через throw  Error() но там асинхронная функция может тоже не попасть надо проверить  или обработать ошибки яндекса внутри try.  Попробуй в консоли проверить если ввести не правильный пароль то куда попадет.

2024-06-12 18:11 UTC, Anastasiia171 commented on packages/client/src/feature/session/login/hooks/useLogin.tsx
> +      const typedError = err as LoginApiError
поправила
добавила unwrap, чтобы падать с ошибками от апишки, немного изменила обертку в  useAuthApi, чтобы rtq query корректно работал

2024-06-13 08:16 UTC, kyzinatra commented on packages/client/src/feature/session/register/hooks/useRegister.tsx
>      e.preventDefault()
Более точно будет `FormEvent<HTMLFormElement>`

2024-06-13 08:16 UTC, DmitriyBrewer approved these changes

2024-06-13 12:28 UTC, ferrum96 approved these changes

2024-06-13 15:15 UTC, merged