Feature/cfg 64 Реализовать одну из игровых механик, описанных в документе с логикой игры
DmitriyBrewer/CodersForceGame pull request #38
Opened 2024-06-15 12:37 UTC by ferrum96

Реализация механики движения дороги относительно игрока

2024-06-15 13:00 UTC, DmitriyBrewer commented on .eslintrc.js
> +    'class-methods-use-this': 'off',
Зачем понадобились новые правила ?

2024-06-15 13:03 UTC, DmitriyBrewer approved these changes

2024-06-15 13:09 UTC, ferrum96 commented on .eslintrc.js
> +    'class-methods-use-this': 'off',
'class-methods-use-this': 'off' - снятие запрета на использование всеми методами класса this
'no-plusplus': 'off' - снятие запрета на использование операторов инкремента (++)
'no-return-assign': 'off' - снятие запрета на присваивание значений в операторе return

2024-06-15 14:01 UTC, kate-lozovaya requested changes
Спасибо за скринкаст!
Оставила несколько комментариев. Посмотри их и призывай меня к ревью.
Из основного - имя переменной должно кратко описывать её предназначение, не стоит сокращать его слишком сильно. Имя переменной из 2-3 слов - это норма, так проще понимать, что происходит в коде, можно понимать связь переменных

2024-06-16 14:53 UTC, ferrum96 commented on packages/client/src/entities/game/index.ts
> +  async loadAssets(cb: (images: { [key: string]: HTMLImageElement }) => void) {
Вынес в отдельный файл с типами

2024-06-16 15:24 UTC, ferrum96 commented on packages/client/src/entities/road/index.ts
> +    const { width: cW } = this.ctx.canvas
Переименовал

2024-06-16 15:24 UTC, ferrum96 commented on packages/client/src/entities/game/index.ts
> +      cb(images)
Переименовал

2024-06-16 15:25 UTC, ferrum96 commented on packages/client/src/entities/game/utils/Load.ts
> +    const images: { [key: string]: HTMLImageElement } = {}
Вынес в отдельный файл с типами

2024-06-16 15:33 UTC, ferrum96 commented on packages/client/src/entities/sprite-image/index.ts
> +  constructor(img: HTMLImageElement, x: number, y: number, width: number, height: number) {
Сделал передачу параметров с одним типом в объекте

2024-06-16 20:04 UTC, kate-lozovaya approved these changes
Спасибо!
Так читать код гораздо удобнее

2024-06-17 07:47 UTC, merged