Feature/cfg 67 Добавить Service Workers
DmitriyBrewer/CodersForceGame pull request #39
Opened 2024-06-15 15:20 UTC by fxmxa

Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета — не только элементы входа и пользовательские настройки, но и сама игра.
Допускается использование плагинов для создания конфигурации воркера, но сам функционал требуется написать самостоятельно в соответствии с материалами из уроков.

https://github.com/DmitriyBrewer/CodersForceGame/assets/158739188/864af7db-7e47-46e7-b1ae-5a801798324d

2024-06-15 15:48 UTC, DmitriyBrewer approved these changes

2024-06-15 19:49 UTC, IvanPeleshok requested changes
Прекрасная работа, интересный подход, но есть пара вопросов

Сложилось впечатление, что код усложняется создаем плагина, который  создаёт некоторые неудобства в поддержке и модификации дальнейшего функционала sw

Если я заблуждаюсь, поправьте меня и распишите преимущество данного подхода
Предлагаю ознакомиться с вопросами и поправить / обоснованный выбранную стратегию интеграции функционала

Хорошего дня :)

2024-06-15 19:49 UTC, IvanPeleshok commented on packages/client/vite-plugin-generate-sw.ts
> +    const CACHE_NAME = 'my-cache-v1';
Насколько данный код легко будет поддерживать, т.к нет поддержки хинтов и линтера

2024-06-15 19:49 UTC, IvanPeleshok commented on packages/client/vite-plugin-generate-sw.ts
> +      await fs.writeFile(resolve(outDir, 'service-worker.js'), swContent)
Такое ощущение, что можно обойтись без генерации файла, а изначально реализовать функционал в .js файле

Подскажите, пожалуйста, в чём преимущество данного подхода по вашему мнению и в чём возможные недостатки?

2024-06-16 06:39 UTC, fxmxa commented on packages/client/vite-plugin-generate-sw.ts
> +      await fs.writeFile(resolve(outDir, 'service-worker.js'), swContent)
Я думаю что можно обойтись без генерации файла, так же как и решить другую задачу разными способами.  Но тогда придется настраивать webpack или другой плагин что бы сформировать список путей, т.к. в проекте добавляются новые файлы, например изображения и все названия файлов формируются с хешем. 

Преимущества на мой взгляд в том что 1) используется только vite и node.js которые уже есть в проекте 2) функции написаны самостоятельно и наглядно видно как формируются файлы, можно достаточно быстро внести изменения.
Недостатки:  то что скрипт sw является строкой. Но так как скрипт не большой и дальнейших изменений не планируется не считаю это большой проблемой.

2024-06-16 06:42 UTC, fxmxa commented on packages/client/vite-plugin-generate-sw.ts
> +    const CACHE_NAME = 'my-cache-v1';
Поддерживать эту часть где формируется строка будет сложнее чем код с автодополнением.

2024-06-16 18:48 UTC, IvanPeleshok approved these changes
Поздравляю, апрув
Интересное решение, отличная работа
Предлагаю посмотреть насколько удобно его будет использовать в дальнейшем

2024-06-17 09:48 UTC, closed without merging